language: python

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

# xenial and sudo needed for 3.7: https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true

install: pip install -e .[test]

script: pytest --cov=totp_generator --cov-report term-missing
