language: python

# xenial and sudo needed for 3.7: https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install: pip install -e .[test]

script: pytest --cov=totp_generator --cov-report term-missing
